define(['jquery'], function ($) {
    return {
    	names: [
    		'Chirpa',
			'Asha Fahn',
			'Logray',
			'Nippet',
			'Paploo',
			'Romba',
			'Teebo',
			'Widdle',
			'Erpham',
			'Deej',
			'Shodu',
			'Weechee',
			'Winda',
			'Kneesaa',
			'Malani',
			'Latara',
			'Chukha-trok',
			'Lumat',
			'Warok',
			'Kaink',
			'Beebee',
			'Snoodoo',
			'Showar',
			'Humpoo',
			'Leemo',
			'Errwaj',
			'Seenee',
			'Cree-lok',
			'Larani',
			'Hurborp',
			'Frick',
			'Perp-bick-lick',
			'Scrumbo',
			'Ark-ack',
			'AIEEEEE',
			'Cruncha',
			'Slig',
			'Lord Bearclaw',
			'Bob',
			'Tekciw',
			'Leep-bi',
			'Chief Smoochface',
			'Hissy',
			'Grumpo Bim-po',
			'Fiddle',
			'Shipple',
			'Emday',
			'Rawr',
			'Kokofo, Stormtrooper Eater',
			'Anger Bear',
			'Peep the Head-Crusher',
			'Stabby Bear',
			'Secret Dog',
			'Gaggle',
			'Harpo',
			'Gork-thot the Cannibal',
			'Muppet',
			'Idolatry Bear',
			'Queen Shuff',
			'Chief Keef',
			'Lord Grub-Grub',
			'Yub-yub the Lesser',
			'Yub-yub the Greater',
			'Glowah',
			'Snuffy'
    	],

        reroll: function () {
            $('.name').text(this.names[Math.floor(Math.random() * this.names.length)]);
        }
    };
});
